[package]
name = "zlgcan-driver"
version = "0.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zlgcan_driver"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28"
rs-can = "0.4"
zlgcan = { version = "0.4", features = ["pyo3"] }

[dev-dependencies]
anyhow = "1.0"
