[package]
name = "zlgcan-driver-py"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zlgcan_driver_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21"
can-type-rs = "1.0.6"
zlgcan_common = "3.0.0-rc"
zlgcan_driver = "3.0.0-rc"