"""
code defines in ZLG-CAN
"""
__all__ = [
    "CANError", "DeviceHandle", "Command", "LIN", "Cloud", "CANMessageType", "Status"
]


class CANError:
    ZCAN_ERROR_CAN_OVERFLOW = 0x0001
    ZCAN_ERROR_CAN_ERRALARM = 0x0002
    ZCAN_ERROR_CAN_PASSIVE = 0x0004
    ZCAN_ERROR_CAN_LOSE = 0x0008
    ZCAN_ERROR_CAN_BUSERR = 0x0010
    ZCAN_ERROR_CAN_BUSOFF = 0x0020
    ZCAN_ERROR_CAN_BUFFER_OVERFLOW = 0x0040

    ZCAN_ERROR_DEVICEOPENED = 0x0100
    ZCAN_ERROR_DEVICEOPEN = 0x0200
    ZCAN_ERROR_DEVICENOTOPEN = 0x0400
    ZCAN_ERROR_BUFFEROVERFLOW = 0x0800
    ZCAN_ERROR_DEVICENOTEXIST = 0x1000
    ZCAN_ERROR_LOADKERNELDLL = 0x2000
    ZCAN_ERROR_CMDFAILED = 0x4000
    ZCAN_ERROR_BUFFERCREATE = 0x8000

    ZCAN_ERROR_CANETE_PORTOPENED = 0x00010000
    ZCAN_ERROR_CANETE_INDEXUSED = 0x00020000
    ZCAN_ERROR_REF_TYPE_ID = 0x00030001
    ZCAN_ERROR_CREATE_SOCKET = 0x00030002
    ZCAN_ERROR_OPEN_CONNECT = 0x00030003
    ZCAN_ERROR_NO_STARTUP = 0x00030004
    ZCAN_ERROR_NO_CONNECTED = 0x00030005
    ZCAN_ERROR_SEND_PARTIAL = 0x00030006
    ZCAN_ERROR_SEND_TOO_FAST = 0x00030007


class DeviceHandle:
    INVALID_DEVICE_HANDLE = 0
    INVALID_CHANNEL_HANDLE = 0


class Command:
    ZCAN_CMD_DESIP = 0
    ZCAN_CMD_DESPORT = 1
    ZCAN_CMD_CHGDESIPANDPORT = 2
    ZCAN_CMD_SRCPORT = 2
    ZCAN_CMD_TCP_TYPE = 4
    ZCAN_TCP_CLIENT = 0
    ZCAN_TCP_SERVER = 1

    ZCAN_CMD_CLIENT_COUNT = 5
    ZCAN_CMD_CLIENT = 6
    ZCAN_CMD_DISCONN_CLINET = 7
    ZCAN_CMD_SET_RECONNECT_TIME = 8


class LIN:
    ZCAN_LIN_MODE_MASTER = 0
    ZCAN_LIN_MODE_SLAVE = 1
    ZCAN_LIN_FLAG_CHK_ENHANCE = 0x01
    ZCAN_LIN_FLAG_VAR_DLC = 0x02


class Cloud:
    ZCLOUD_MAX_DEVICES = 100
    ZCLOUD_MAX_CHANNEL = 16


class CANMessageType:
    ZCAN_TYPE_CAN = 0
    ZCAN_TYPE_CANFD = 1
    ZCAN_TYPE_ALL_DATA = 2


class Status:
    ZCAN_STATUS_ERR = 0
    ZCAN_STATUS_OK = 1
    ZCAN_STATUS_ONLINE = 2
    ZCAN_STATUS_OFFLINE = 3
    ZCAN_STATUS_UNSUPPORTED = 4
